highlighter: rouge
gems: [jekyll-paginate]
encoding: utf-8
paginate: 8
paginate_path: "page:num"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

name: jcf
bio: jcf.me
url: http://jcf.me/
email: xudadi811@gmail.com
logo: "/assets/img/def/logo.jpg"
fav: "/favicon.ico"

defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_ad: true

navs:
  - 
    href: /blog/
    label: 博客
  - 
    href: http://weibo.xudadi.com
    label: 微博
  -
    href: https://status.xudadi.com
    label: 状态
  -
    href: /feed.xml
    label: 订阅
  - 
    href: /about/
    label: 关于

# ---------------- #
#      Socials     #
# ---------------- #
github_id: xudadi
weibo_id: xudadi811
twitter_id: xudadi
